from flask import Blueprint
from flask import request

from ..const.json_const import true, false, null
from ..const.filepath import CONFIG_JSON, VERSION_JSON
from ..util.const_json_loader import const_json_loader
from ..util.player_data import player_data_decorator

bp_common = Blueprint("bp_common", __name__)


@bp_common.route("/common/config", methods=["POST"])
def common_config():
    request_json = request.get_json()
    response = {
        "Code": 200,
        "Data": {
            "AppConfig": {
                "AGREEMENT_POPUP_TYPE": "Browser",
                "APPLE_CURRENCY_BLOCK_LIST": null,
                "APP_CLIENT_LANG": ["en"],
                "APP_DEBUG": 0,
                "APP_GL": "en",
                "BIND_METHOD": ["google", "apple_hk", "facebook"],
                "CAPTCHA_ENABLED": false,
                "CLIENT_LOG_REPORTING": {"ENABLE": true},
                "CREDIT_INVESTIGATION": "0.0",
                "DESTROY_USER_DAYS": 15,
                "DESTROY_USER_ENABLE": 1,
                "DETECTION_ADDRESS": {
                    "AUTO": {
                        "DNS": null,
                        "HTTP": [
                            "https://ark-us-static-online.yo-star.com",
                            "https://en-sdk-api.yostarplat.com",
                        ],
                        "MTR": [
                            "https://ark-us-static-online.yo-star.com",
                            "https://en-sdk-api.yostarplat.com",
                        ],
                        "PING": null,
                        "TCP": null,
                    },
                    "ENABLE": true,
                    "INTERNET": "https://www.google.com",
                },
                "ENABLE_AGREEMENT": true,
                "ENABLE_MULTI_LANG_AGREEMENT": false,
                "ENABLE_TEXT_REVIEW": true,
                "ERROR_CODE": "3.2",
                "FILE_DOMAIN": "https://storage.googleapis.com/sdkplat-en-prod",
                "GEETEST_ENABLE": false,
                "GEETEST_ID": "",
                "GOOGLE_ANALYTICS_MEASUREMENT_ID": "",
                "MIGRATE_POPUP": true,
                "NICKNAME_REG": "^[A-Za-z0-9]{2,20}$",
                "POPUP": {
                    "Data": [
                        {"Lang": "ja", "Text": "Yostar IDを作成"},
                        {"Lang": "en", "Text": "Create a Yostar account"},
                        {"Lang": "kr", "Text": "YOSTAR 계정 가입하기"},
                        {"Lang": "fr", "Text": "Créez votre compte Yostar"},
                        {"Lang": "de", "Text": "Einen Yostar-Account erstellen"},
                    ],
                    "Enable": true,
                },
                "PRIVACY_AGREEMENT": "0.1",
                "RECHARGE_LIMIT": {
                    "Enable": false,
                    "IsOneLimit": false,
                    "Items": [],
                    "OneLimitAmount": 0,
                },
                "SHARE": {
                    "CaptureScreen": {"AutoCloseDelay": 0, "Enabled": false},
                    "Facebook": {"AppID": "", "Enabled": true},
                    "Instagram": {"Enabled": true},
                    "Kakao": {"AppKey": "", "Enabled": false},
                    "Naver": {"Enabled": false},
                    "Twitter": {"Enabled": true},
                },
                "SLS": {
                    "ACCESS_KEY_ID": "7b5d0ffd0943f26704fc547a871c68b1b5d56b5c9caeb354205b81f445d7af59",
                    "ACCESS_KEY_SECRET": "4a5e9cc8a50819290c9bfa1fedc79da7c50e85189a05eb462a3d28a7688eabb0",
                    "ENABLE": true,
                },
                "SURVEY_POPUP_TYPE": "Webview",
                "UDATA": {"Enable": false, "URL": ""},
                "USER_AGREEMENT": "0.1",
                "YOSTAR_PREFIX": "yoyo",
            },
            "EuropeUnion": false,
            "StoreConfig": {
                "ADJUST_APPID": "mgnbk3cl8oao",
                "ADJUST_CHARGEEVENTTOKEN": "",
                "ADJUST_ENABLED": 1,
                "ADJUST_EVENTTOKENS": {
                    "account_create": "ukxsve",
                    "add_friend": "758t8k",
                    "behavior_check": "1nbtpr",
                    "behavior_check:": "1nbtpr",
                    "behavior_verification_failed": "8sy2jj",
                    "behavior_verification_failed:": "8sy2jj",
                    "chapter_main_00-11": "a1j8j9",
                    "chapter_main_00-11#f#": "swn8kq",
                    "chapter_main_01-09": "m28f4h",
                    "chapter_main_01-12": "fey9e8",
                    "chapter_main_01-12#f#": "v8ebus",
                    "chapter_main_02-02": "1ny3j6",
                    "chapter_main_02-03": "g4zql5",
                    "chapter_main_02-10": "k3x80e",
                    "chapter_main_02-10#f#": "mqb9dm",
                    "chapter_main_03-04": "94uuhl",
                    "chapter_main_03-08": "sbjif7",
                    "chapter_main_03-08#f#": "h5w3gq",
                    "chapter_main_04-10": "x9daot",
                    "chapter_main_04-10#f#": "cesrgm",
                    "confirm_order": "kqsjt6",
                    "control_center_level_2": "9munvb",
                    "control_center_level_3": "tijnll",
                    "control_center_level_4": "iqdwzg",
                    "control_center_level_5": "ckyph4",
                    "elite_2": "n5thdx",
                    "first_purchase_sdk": "5juwoc",
                    "purchase": "fmq7ij",
                    "purchase_click": "bgpbnf",
                    "purchase_click_CASH": "msczc0",
                    "purchase_click_GP_LEVEL": "30qd2y",
                    "purchase_click_GP_MONTHLY": "ditx2u",
                    "purchase_click_GP_ONCE": "rdrgiy",
                    "purchase_click_GP_WEEKLY": "t4l0ih",
                    "purchase_click_MONTLYCARD": "a2m487",
                    "purchase_click_SKIN": "onyk20",
                    "purchase_click_giftbag": "uubu7h",
                    "purchase_complete": "95xxlq",
                    "purchase_complete_CASH": "ledrge",
                    "purchase_complete_GP_LEVEL": "h12oqc",
                    "purchase_complete_GP_MONTHLY": "kmkhji",
                    "purchase_complete_GP_ONCE": "43gxmt",
                    "purchase_complete_GP_WEEKLY": "sttrkm",
                    "purchase_complete_MONTLYCARD": "q09wwa",
                    "purchase_complete_SKIN": "im02o0",
                    "purchase_first": "994twt",
                    "role_create": "4x8lau",
                    "role_info_upload": "kbs9zm",
                    "role_level_1": "n79h7k",
                    "role_level_10": "hk4w6q",
                    "role_level_100": "59zt8r",
                    "role_level_11": "ywojnd",
                    "role_level_12": "dj1zo5",
                    "role_level_13": "lkx9xp",
                    "role_level_14": "40f381",
                    "role_level_15": "nfjczf",
                    "role_level_16": "yoc2nh",
                    "role_level_17": "ufgz8h",
                    "role_level_18": "o3rl6j",
                    "role_level_19": "m7ai7a",
                    "role_level_2": "el7dfm",
                    "role_level_20": "ubbbk5",
                    "role_level_25": "92p5q2",
                    "role_level_3": "j3mid9",
                    "role_level_30": "z7rya7",
                    "role_level_35": "j2yw2h",
                    "role_level_4": "j6smfu",
                    "role_level_40": "j7hgf6",
                    "role_level_45": "nqyq2g",
                    "role_level_5": "grqvhm",
                    "role_level_50": "565mnv",
                    "role_level_55": "ksafg7",
                    "role_level_6": "gh5e3b",
                    "role_level_60": "ocju9w",
                    "role_level_65": "vcr1rf",
                    "role_level_7": "sfos34",
                    "role_level_70": "eostne",
                    "role_level_75": "bvxokb",
                    "role_level_8": "dl6yh4",
                    "role_level_80": "gjpsfb",
                    "role_level_85": "q4uat1",
                    "role_level_9": "m29e7b",
                    "role_level_90": "ka9hqc",
                    "role_level_95": "6f86hp",
                    "role_login": "i8z34y",
                    "secondday_retention": "37sg9f",
                    "seventhday_retention": "2gzstr",
                    "story_read_end": "1afttn",
                    "story_read_start": "talwn3",
                    "sys_language": "dblooz",
                    "tutorial_complete_1": "fi4yye",
                    "tutorial_complete_2": "fqziby",
                    "tutorial_complete_3": "2sspql",
                    "tutorial_complete_4": "vjgy5w",
                    "tutorial_complete_5": "15ar6n",
                    "tutorial_complete_6": "7ofj0k",
                    "tutorial_complete_7": "czzk3v",
                    "tutorial_complete_8": "kst3sj",
                    "tutorial_complete_9": "tucsy8",
                    "tutorial_complete_9:": "tucsy8",
                    "weekly_mission:": "7q2dqy",
                    "yostarsdk_account_bind": "l4ppok",
                    "yostarsdk_behavior_check": "4vgkme",
                    "yostarsdk_cancle_del_account": "muubjw",
                    "yostarsdk_del_account": "35yquv",
                    "yostarsdk_del_account_intention": "wy5miy",
                    "yostarsdk_init": "nv4clf",
                    "yostarsdk_pay_illegal_currency": "ioap40",
                    "yostarsdk_user_login": "5rgxoy",
                    "yostarsdk_user_open_review": "kemond",
                    "yostarsdk_user_open_survey": "ihy1kc",
                    "yostarsdk_user_paid_level": "eeqgsd",
                    "yostarsdk_user_pay_canceled": "lk2vyt",
                    "yostarsdk_user_pay_intention": "kzjvyk",
                    "yostarsdk_user_share": "as7eww",
                    "yostarsdk_user_share_intention": "ctcic6",
                    "yostarsdk_user_switch_account": "vxj8oh",
                    "ysdk_err": "9urmkm",
                    "ysdk_err:": "9urmkm",
                },
                "ADJUST_ISDEBUG": 0,
                "AI_HELP": {"DisplayType": "Browser", "Enable": 1, "Mode": "robot"},
                "ENABLED_PAY": {
                    "GMOAu": false,
                    "GMOCreditcard": false,
                    "GMOCvs": false,
                    "GMODocomo": false,
                    "GMOPaypal": false,
                    "GMOPaypay": false,
                    "GMOSoftbank": false,
                    "PAYPAL_ENABLED": false,
                    "STEAM_ENABLED": false,
                    "STRIPE_ENABLED": false,
                    "TOSS_ENABLED": false,
                    "WEBMONEY_ENABLED": false,
                },
                "FACEBOOK_APPID": "1168277143355360",
                "FACEBOOK_CLIENT_TOKEN": "",
                "FACEBOOK_SECRET": "3efc73a899488866a12bcdcbb6ae2158",
                "FIREBASE_ENABLED": 1,
                "GMO_CC_JS": "https://",
                "GMO_CC_KEY": "",
                "GMO_CC_SHOPID": "",
                "GMO_PAY_CHANNEL": {
                    "GMOAu": false,
                    "GMOCreditcard": false,
                    "GMOCvs": false,
                    "GMODocomo": false,
                    "GMOPaypal": false,
                    "GMOPaypay": false,
                    "GMOSoftbank": false,
                },
                "GMO_PAY_ENABLED": false,
                "GOOGLE_CLIENT_ID": "456547535367-53k3p07sjhionhf55vg586bpcf1i4ffu.apps.googleusercontent.com",
                "GUEST_CREATE_METHOD": 0,
                "GUIDE_POPUP": {"DATA": null, "ENABLE": 0},
                "GoogleClientID": "456547535367-53k3p07sjhionhf55vg586bpcf1i4ffu.apps.googleusercontent.com",
                "LOGIN": {
                    "DEFAULT": "yostar",
                    "ICON_SIZE": "big",
                    "SORT": ["google", "facebook", "device"],
                },
                "ONE_STORE_LICENSE_KEY": "",
                "PAYPAL_ENABLED": false,
                "REMOTE_CONFIG": [],
                "SAMSUNG_SANDBOX_MODE": false,
                "STEAM_APPID": "",
                "STEAM_ENABLED": false,
                "STEAM_PAY_APPID": "",
                "STRIPE_ENABLED": false,
                "TOSS_ENABLED": false,
                "TWITTER_KEY": "",
                "TWITTER_SECRET": "",
                "WEBMONEY_ENABLED": false,
            },
        },
        "Msg": "OK",
    }
    return response


@bp_common.route("/common/client-info", methods=["POST"])
def common_client_info():
    request_json = request.get_json()
    response = {"Code": 200, "Data": {"EuropeUnion": false}, "Msg": "OK"}
    return response


@bp_common.route("/common/version", methods=["POST"])
def common_version():
    request_json = request.get_json()
    response = {
        "Code": 200,
        "Data": {
            "Agreement": [
                {
                    "Version": "0.1",
                    "Type": "user_agreement",
                    "Title": "用户协议",
                    "Content": "",
                    "Lang": "en",
                },
                {
                    "Version": "0.1",
                    "Type": "privacy_agreement",
                    "Title": "隐私政策",
                    "Content": "",
                    "Lang": "en",
                },
            ],
            "ErrorCode": "3.2",
        },
        "Msg": "OK",
    }
    return response
