CONFIG_JSON = "conf/config.json"
VERSION_JSON = "conf/version.json"

TMPL_JSON = "data/tmpl.json"

SKIN_TABLE = "res/excel/skin_table.json"
CHARWORD_TABLE = "res/excel/charword_table.json"
UNIEQUIP_TABLE = "res/excel/uniequip_table.json"
CHARACTER_TABLE = "res/excel/character_table.json"
STORY_TABLE = "res/excel/story_table.json"
STAGE_TABLE = "res/excel/stage_table.json"
HANDBOOK_INFO_TABLE = "res/excel/handbook_info_table.json"
RETRO_TABLE = "res/excel/retro_table.json"
DISPLAY_META_TABLE = "res/excel/display_meta_table.json"
MEDAL_TABLE = "res/excel/medal_table.json"
STORY_REVIEW_TABLE = "res/excel/story_review_table.json"
STORY_REVIEW_META_TABLE = "res/excel/story_review_meta_table.json"
ENEMY_HANDBOOK_TABLE = "res/excel/enemy_handbook_table.json"
ACTIVITY_TABLE = "res/excel/activity_table.json"
