from fastapi import APIRouter
from fastapi import Request

from ..const.json_const import true, false, null
from ..const.filepath import CONFIG_JSON, VERSION_JSON
from ..util.const_json_loader import const_json_loader
from ..util.player_data import player_data_decorator

router = APIRouter()


@router.post("/common/config")
async def common_config(request: Request):
    request_json = await request.json()
    response = {
        "Code": 200,
        "Data": {
            "AppConfig": {
                "AGREEMENT_POPUP_TYPE": "Browser",
                "APPLE_CURRENCY_BLOCK_LIST": null,
                "APP_CLIENT_LANG": ["en"],
                "APP_DEBUG": 0,
                "APP_GL": "en",
                "BIND_METHOD": ["google", "apple_hk", "facebook"],
                "CAPTCHA_ENABLED": false,
                "CLIENT_LOG_REPORTING": {"ENABLE": true},
                "CREDIT_INVESTIGATION": "0.0",
                "DESTROY_USER_DAYS": 15,
                "DESTROY_USER_ENABLE": 1,
                "DETECTION_ADDRESS": {
                    "AUTO": {
                        "DNS": null,
                        "HTTP": [
                            "https://ark-us-static-online.yo-star.com",
                            "https://en-sdk-api.yostarplat.com",
                        ],
                        "MTR": [
                            "https://ark-us-static-online.yo-star.com",
                            "https://en-sdk-api.yostarplat.com",
                        ],
                        "PING": null,
                        "TCP": null,
                    },
                    "ENABLE": true,
                    "INTERNET": "https://www.google.com",
                },
                "ENABLE_AGREEMENT": true,
                "ENABLE_MULTI_LANG_AGREEMENT": false,
                "ENABLE_TEXT_REVIEW": true,
                "ERROR_CODE": "3.2",
                "FILE_DOMAIN": "https://storage.googleapis.com/sdkplat-en-prod",
                "GEETEST_ENABLE": false,
                "GEETEST_ID": "",
                "GOOGLE_ANALYTICS_MEASUREMENT_ID": "",
                "MIGRATE_POPUP": true,
                "NICKNAME_REG": "^[A-Za-z0-9]{2,20}$",
                "POPUP": {
                    "Data": [
                        {"Lang": "ja", "Text": "Yostar IDを作成"},
                        {"Lang": "en", "Text": "Create a Yostar account"},
                        {"Lang": "kr", "Text": "YOSTAR 계정 가입하기"},
                        {"Lang": "fr", "Text": "Créez votre compte Yostar"},
                        {"Lang": "de", "Text": "Einen Yostar-Account erstellen"},
                    ],
                    "Enable": true,
                },
                "PRIVACY_AGREEMENT": "0.1",
                "RECHARGE_LIMIT": {
                    "Enable": false,
                    "IsOneLimit": false,
                    "Items": [],
                    "OneLimitAmount": 0,
                },
                "SHARE": {
                    "CaptureScreen": {"AutoCloseDelay": 0, "Enabled": false},
                    "Facebook": {"AppID": "", "Enabled": true},
                    "Instagram": {"Enabled": true},
                    "Kakao": {"AppKey": "", "Enabled": false},
                    "Naver": {"Enabled": false},
                    "Twitter": {"Enabled": true},
                },
                "SLS": {
                    "ACCESS_KEY_ID": "7b5d0ffd0943f26704fc547a871c68b1b5d56b5c9caeb354205b81f445d7af59",
                    "ACCESS_KEY_SECRET": "4a5e9cc8a50819290c9bfa1fedc79da7c50e85189a05eb462a3d28a7688eabb0",
                    "ENABLE": true,
                },
                "SURVEY_POPUP_TYPE": "Webview",
                "UDATA": {"Enable": false, "URL": ""},
                "USER_AGREEMENT": "0.1",
                "YOSTAR_PREFIX": "yoyo",
            },
            "EuropeUnion": false,
            "StoreConfig": {
                "ADJUST_APPID": "mgnbk3cl8oao",
                "ADJUST_CHARGEEVENTTOKEN": "",
                "ADJUST_ENABLED": 1,
                "ADJUST_EVENTTOKENS": {
                    "account_create": "ukxsve",
                    "add_friend": "758t8k",
                    "behavior_check": "1nbtpr",
                    "behavior_check:": "1nbtpr",
                    "behavior_verification_failed": "8sy2jj",
                    "behavior_verification_failed:": "8sy2jj",
                    "chapter_main_00-11": "a1j8j9",
                    "chapter_main_00-11#f#": "swn8kq",
                    "chapter_main_01-09": "m28f4h",
                    "chapter_main_01-12": "fey9e8",
                    "chapter_main_01-12#f#": "v8ebus",
                    "chapter_main_02-02": "1ny3j6",
                    "chapter_main_02-03": "g4zql5",
                    "chapter_main_02-10": "k3x80e",
                    "chapter_main_02-10#f#": "mqb9dm",
                    "chapter_main_03-04": "94uuhl",
                    "chapter_main_03-08": "sbjif7",
                    "chapter_main_03-08#f#": "h5w3gq",
                    "chapter_main_04-10": "x9daot",
                    "chapter_main_04-10#f#": "cesrgm",
                    "confirm_order": "kqsjt6",
                    "control_center_level_2": "9munvb",
                    "control_center_level_3": "tijnll",
                    "control_center_level_4": "iqdwzg",
                    "control_center_level_5": "ckyph4",
                    "elite_2": "n5thdx",
                    "first_purchase_sdk": "5juwoc",
                    "purchase": "fmq7ij",
                    "purchase_click": "bgpbnf",
                    "purchase_click_CASH": "msczc0",
                    "purchase_click_GP_LEVEL": "30qd2y",
                    "purchase_click_GP_MONTHLY": "ditx2u",
                    "purchase_click_GP_ONCE": "rdrgiy",
                    "purchase_click_GP_WEEKLY": "t4l0ih",
                    "purchase_click_MONTLYCARD": "a2m487",
                    "purchase_click_SKIN": "onyk20",
                    "purchase_click_giftbag": "uubu7h",
                    "purchase_complete": "95xxlq",
                    "purchase_complete_CASH": "ledrge",
                    "purchase_complete_GP_LEVEL": "h12oqc",
                    "purchase_complete_GP_MONTHLY": "kmkhji",
                    "purchase_complete_GP_ONCE": "43gxmt",
                    "purchase_complete_GP_WEEKLY": "sttrkm",
                    "purchase_complete_MONTLYCARD": "q09wwa",
                    "purchase_complete_SKIN": "im02o0",
                    "purchase_first": "994twt",
                    "role_create": "4x8lau",
                    "role_info_upload": "kbs9zm",
                    "role_level_1": "n79h7k",
                    "role_level_10": "hk4w6q",
                    "role_level_100": "59zt8r",
                    "role_level_11": "ywojnd",
                    "role_level_12": "dj1zo5",
                    "role_level_13": "lkx9xp",
                    "role_level_14": "40f381",
                    "role_level_15": "nfjczf",
                    "role_level_16": "yoc2nh",
                    "role_level_17": "ufgz8h",
                    "role_level_18": "o3rl6j",
                    "role_level_19": "m7ai7a",
                    "role_level_2": "el7dfm",
                    "role_level_20": "ubbbk5",
                    "role_level_25": "92p5q2",
                    "role_level_3": "j3mid9",
                    "role_level_30": "z7rya7",
                    "role_level_35": "j2yw2h",
                    "role_level_4": "j6smfu",
                    "role_level_40": "j7hgf6",
                    "role_level_45": "nqyq2g",
                    "role_level_5": "grqvhm",
                    "role_level_50": "565mnv",
                    "role_level_55": "ksafg7",
                    "role_level_6": "gh5e3b",
                    "role_level_60": "ocju9w",
                    "role_level_65": "vcr1rf",
                    "role_level_7": "sfos34",
                    "role_level_70": "eostne",
                    "role_level_75": "bvxokb",
                    "role_level_8": "dl6yh4",
                    "role_level_80": "gjpsfb",
                    "role_level_85": "q4uat1",
                    "role_level_9": "m29e7b",
                    "role_level_90": "ka9hqc",
                    "role_level_95": "6f86hp",
                    "role_login": "i8z34y",
                    "secondday_retention": "37sg9f",
                    "seventhday_retention": "2gzstr",
                    "story_read_end": "1afttn",
                    "story_read_start": "talwn3",
                    "sys_language": "dblooz",
                    "tutorial_complete_1": "fi4yye",
                    "tutorial_complete_2": "fqziby",
                    "tutorial_complete_3": "2sspql",
                    "tutorial_complete_4": "vjgy5w",
                    "tutorial_complete_5": "15ar6n",
                    "tutorial_complete_6": "7ofj0k",
                    "tutorial_complete_7": "czzk3v",
                    "tutorial_complete_8": "kst3sj",
                    "tutorial_complete_9": "tucsy8",
                    "tutorial_complete_9:": "tucsy8",
                    "weekly_mission:": "7q2dqy",
                    "yostarsdk_account_bind": "l4ppok",
                    "yostarsdk_behavior_check": "4vgkme",
                    "yostarsdk_cancle_del_account": "muubjw",
                    "yostarsdk_del_account": "35yquv",
                    "yostarsdk_del_account_intention": "wy5miy",
                    "yostarsdk_init": "nv4clf",
                    "yostarsdk_pay_illegal_currency": "ioap40",
                    "yostarsdk_user_login": "5rgxoy",
                    "yostarsdk_user_open_review": "kemond",
                    "yostarsdk_user_open_survey": "ihy1kc",
                    "yostarsdk_user_paid_level": "eeqgsd",
                    "yostarsdk_user_pay_canceled": "lk2vyt",
                    "yostarsdk_user_pay_intention": "kzjvyk",
                    "yostarsdk_user_share": "as7eww",
                    "yostarsdk_user_share_intention": "ctcic6",
                    "yostarsdk_user_switch_account": "vxj8oh",
                    "ysdk_err": "9urmkm",
                    "ysdk_err:": "9urmkm",
                },
                "ADJUST_ISDEBUG": 0,
                "AI_HELP": {"DisplayType": "Browser", "Enable": 1, "Mode": "robot"},
                "ENABLED_PAY": {
                    "GMOAu": false,
                    "GMOCreditcard": false,
                    "GMOCvs": false,
                    "GMODocomo": false,
                    "GMOPaypal": false,
                    "GMOPaypay": false,
                    "GMOSoftbank": false,
                    "PAYPAL_ENABLED": false,
                    "STEAM_ENABLED": false,
                    "STRIPE_ENABLED": false,
                    "TOSS_ENABLED": false,
                    "WEBMONEY_ENABLED": false,
                },
                "FACEBOOK_APPID": "1168277143355360",
                "FACEBOOK_CLIENT_TOKEN": "",
                "FACEBOOK_SECRET": "3efc73a899488866a12bcdcbb6ae2158",
                "FIREBASE_ENABLED": 1,
                "GMO_CC_JS": "https://",
                "GMO_CC_KEY": "",
                "GMO_CC_SHOPID": "",
                "GMO_PAY_CHANNEL": {
                    "GMOAu": false,
                    "GMOCreditcard": false,
                    "GMOCvs": false,
                    "GMODocomo": false,
                    "GMOPaypal": false,
                    "GMOPaypay": false,
                    "GMOSoftbank": false,
                },
                "GMO_PAY_ENABLED": false,
                "GOOGLE_CLIENT_ID": "456547535367-53k3p07sjhionhf55vg586bpcf1i4ffu.apps.googleusercontent.com",
                "GUEST_CREATE_METHOD": 0,
                "GUIDE_POPUP": {"DATA": null, "ENABLE": 0},
                "GoogleClientID": "456547535367-53k3p07sjhionhf55vg586bpcf1i4ffu.apps.googleusercontent.com",
                "LOGIN": {
                    "DEFAULT": "yostar",
                    "ICON_SIZE": "big",
                    "SORT": ["google", "facebook", "device"],
                },
                "ONE_STORE_LICENSE_KEY": "",
                "PAYPAL_ENABLED": false,
                "REMOTE_CONFIG": [],
                "SAMSUNG_SANDBOX_MODE": false,
                "STEAM_APPID": "",
                "STEAM_ENABLED": false,
                "STEAM_PAY_APPID": "",
                "STRIPE_ENABLED": false,
                "TOSS_ENABLED": false,
                "TWITTER_KEY": "",
                "TWITTER_SECRET": "",
                "WEBMONEY_ENABLED": false,
            },
        },
        "Msg": "OK",
    }
    return response


@router.post("/common/client-info")
async def common_client_info(request: Request):
    request_json = await request.json()
    response = {"Code": 200, "Data": {"EuropeUnion": false}, "Msg": "OK"}
    return response


@router.post("/common/version")
async def common_version(request: Request):
    request_json = await request.json()
    response = {
        "Code": 200,
        "Data": {
            "Agreement": [
                {
                    "Version": "0.1",
                    "Type": "user_agreement",
                    "Title": "用户协议",
                    "Content": "",
                    "Lang": "en",
                },
                {
                    "Version": "0.1",
                    "Type": "privacy_agreement",
                    "Title": "隐私政策",
                    "Content": "",
                    "Lang": "en",
                },
            ],
            "ErrorCode": "3.2",
        },
        "Msg": "OK",
    }
    return response


@router.post("/common/client-code")
async def common_client_code(request: Request):
    request_json = await request.json()
    response = {
        "Code": 200,
        "Data": {
            "CodeList": [
                {"Code": 200350, "Value": "Order creation failed.", "Type": "pop"},
                {"Code": 200170, "Value": "Illegal purchase request.", "Type": "pop"},
                {
                    "Code": 100246,
                    "Value": "Current client doesn't support Sign in with Apple.",
                    "Type": "pop",
                },
                {"Code": 400133, "Value": "Unable to unbind email.", "Type": "pop"},
                {
                    "Code": 200152,
                    "Value": "Order already completed. Please do not submit repeatedly.",
                    "Type": "pop",
                },
                {
                    "Code": 500101,
                    "Value": "Order failed. This order has been refunded.",
                    "Type": "pop",
                },
                {
                    "Code": 400134,
                    "Value": "Unbinding failed. This account is not authorized or has been unbound repeatedly.",
                    "Type": "pop",
                },
                {
                    "Code": 200151,
                    "Value": "Could not verify this purchase.",
                    "Type": "pop",
                },
                {
                    "Code": 400215,
                    "Value": "Binding failed. The Yostar account has been bound with another in-game account.",
                    "Type": "pop",
                },
                {
                    "Code": 100502,
                    "Value": "You're not in the Allowlist.",
                    "Type": "pop",
                },
                {"Code": 300203, "Value": "Channel does not exist.", "Type": "pop"},
                {
                    "Code": 100236,
                    "Value": "This login method is not available.",
                    "Type": "pop",
                },
                {
                    "Code": 400200,
                    "Value": "Binding failed. This account has been bound to another Yostar account.",
                    "Type": "pop",
                },
                {
                    "Code": 902001,
                    "Value": "This error code has existed.",
                    "Type": "pop",
                },
                {
                    "Code": 901001,
                    "Value": "This application has existed.",
                    "Type": "pop",
                },
                {
                    "Code": 400201,
                    "Value": "Binding failed. The Yostar account has been bound to another third-party account.",
                    "Type": "pop",
                },
                {
                    "Code": 100900,
                    "Value": "The user is detected as a new user.",
                    "Type": "toast",
                },
                {
                    "Code": 400400,
                    "Value": "Account migration failed. Please contact Customer Service.",
                    "Type": "pop",
                },
                {
                    "Code": 400132,
                    "Value": "Please bind an email address before unbinding your account.",
                    "Type": "pop",
                },
                {
                    "Code": 100901,
                    "Value": "The user is detected as an already existing user.",
                    "Type": "toast",
                },
                {
                    "Code": 100801,
                    "Value": "Questionnaire request failed.",
                    "Type": "toast",
                },
                {"Code": 300204, "Value": "Client version outdated.", "Type": "pop"},
                {
                    "Code": 100802,
                    "Value": "Questionnaire ID does not exist.",
                    "Type": "toast",
                },
                {
                    "Code": 400130,
                    "Value": "This Yostar account has been banned.",
                    "Type": "pop",
                },
                {
                    "Code": 100235,
                    "Value": "Account deletion is not available.",
                    "Type": "pop",
                },
                {
                    "Code": 400202,
                    "Value": "Already bound. Unable to bind repeatedly.",
                    "Type": "toast",
                },
                {
                    "Code": 400214,
                    "Value": "This account does not exist.",
                    "Type": "pop",
                },
                {
                    "Code": 400131,
                    "Value": "Invalid nickname. Please re-enter.",
                    "Type": "toast",
                },
                {
                    "Code": 400135,
                    "Value": "Your nickname contains invalid characters. Please enter a new one.",
                    "Type": "toast",
                },
                {"Code": -1, "Value": "Unknown Error.", "Type": "pop"},
                {
                    "Code": 200180,
                    "Value": "Payment succeeded. Now packing.",
                    "Type": "toast",
                },
                {"Code": 100132, "Value": "Login canceled.", "Type": "toast"},
                {
                    "Code": 100303,
                    "Value": "The verification code is incorrect.",
                    "Type": "toast",
                },
                {
                    "Code": 300101,
                    "Value": "Sorry, sharing is currently not available.",
                    "Type": "toast",
                },
                {
                    "Code": 500301,
                    "Value": "Item ID of the game has existed.",
                    "Type": "pop",
                },
                {
                    "Code": 300102,
                    "Value": "The app is not installed in this device.",
                    "Type": "toast",
                },
                {
                    "Code": 100200,
                    "Value": "The third-party account provided has been bound to another user account.",
                    "Type": "pop",
                },
                {
                    "Code": 100202,
                    "Value": "Already bound. Unable to bind repeatedly.",
                    "Type": "pop",
                },
                {
                    "Code": 400218,
                    "Value": "Binding failed. The Yostar account hasn't been bound to a third-party account.",
                    "Type": "pop",
                },
                {
                    "Code": 400217,
                    "Value": "Binding failed. There're abnormal activities with your account.",
                    "Type": "pop",
                },
                {
                    "Code": 100213,
                    "Value": "Unable to unbind. Please bind your account to at least one third-party account.",
                    "Type": "pop",
                },
                {
                    "Code": 400136,
                    "Value": "Your nickname is being reviewed. Please try again later.",
                    "Type": "toast",
                },
                {
                    "Code": 100201,
                    "Value": "The user account has been bound to another third-party account. Please unbind first.",
                    "Type": "pop",
                },
                {
                    "Code": 400213,
                    "Value": "Unbinding failed. Please bind the Yostar account to at least one third-party account.",
                    "Type": "pop",
                },
                {
                    "Code": 300205,
                    "Value": "Item requested doesn't exist.",
                    "Type": "pop",
                },
                {
                    "Code": 100306,
                    "Value": "Invalid Yostar account format.",
                    "Type": "pop",
                },
                {
                    "Code": 500302,
                    "Value": "Item ID of the store has existed.",
                    "Type": "pop",
                },
                {
                    "Code": 400216,
                    "Value": "Binding failed. This account has been bound to another Yostar account.",
                    "Type": "pop",
                },
                {
                    "Code": 400140,
                    "Value": "Recovery email can't be the same as Primary email. Please enter a new one.",
                    "Type": "toast",
                },
                {
                    "Code": 100811,
                    "Value": "PGS Parameter configuration Error",
                    "Type": "toast",
                },
                {
                    "Code": 400141,
                    "Value": "Query failed. Abnormality occurred in Text Moderation Interface.",
                    "Type": "toast",
                },
                {
                    "Code": 400139,
                    "Value": "Data verification has expired. Please try again.",
                    "Type": "toast",
                },
                {
                    "Code": 100814,
                    "Value": "PGS Parameter configuration Error",
                    "Type": "toast",
                },
                {
                    "Code": 100812,
                    "Value": "PGS Parameter configuration Error",
                    "Type": "toast",
                },
                {
                    "Code": 100803,
                    "Value": "Questionnaire has expired. Please reissue.",
                    "Type": "toast",
                },
                {
                    "Code": 400138,
                    "Value": "The game account has been bound to another Google Play Games account, and the Google Play Games account currently logged in has also been bound to another game account.",
                    "Type": "toast",
                },
                {
                    "Code": 100813,
                    "Value": "PGS Parameter configuration Error",
                    "Type": "toast",
                },
                {
                    "Code": 400137,
                    "Value": "Guest account can't be bound to PGS.",
                    "Type": "toast",
                },
                {
                    "Code": 400219,
                    "Value": "It's not allowed that YostarID is only bound to a PGS account.",
                    "Type": "toast",
                },
                {
                    "Code": 100902,
                    "Value": "New Guest account login on American server and Korean server.",
                    "Type": "toast",
                },
                {
                    "Code": 400143,
                    "Value": "This email address is currently bound as a recovery email and cannot be set as the primary email",
                    "Type": "toast",
                },
                {
                    "Code": 400144,
                    "Value": "This Yostar account has not been bound to a user account and cannot change its binding",
                    "Type": "toast",
                },
                {
                    "Code": 400142,
                    "Value": "User cancelled the authorization",
                    "Type": "toast",
                },
                {
                    "Code": 100401,
                    "Value": "Please try again after logging in.",
                    "Type": "toast",
                },
                {
                    "Code": 100100,
                    "Value": "The device has been restricted.",
                    "Type": "pop",
                },
                {"Code": 200130, "Value": "Order creation failed.", "Type": "pop"},
                {
                    "Code": 200320,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100228,
                    "Value": "The account has been deleted. Login failed.",
                    "Type": "pop",
                },
                {
                    "Code": 100190,
                    "Value": "Account verification failed.",
                    "Type": "toast",
                },
                {
                    "Code": 100242,
                    "Value": "Apple authorization failed.",
                    "Type": "toast",
                },
                {
                    "Code": 100500,
                    "Value": "System error. Please contact Customer Service.",
                    "Type": "pop",
                },
                {"Code": 200160, "Value": "Illegal purchase request.", "Type": "pop"},
                {"Code": 300200, "Value": "The game does not exist.", "Type": "pop"},
                {
                    "Code": 200260,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100240,
                    "Value": "Apple authorization failed.",
                    "Type": "toast",
                },
                {
                    "Code": 200270,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100230,
                    "Value": "Initialization failed, please try again.",
                    "Type": "pop",
                },
                {
                    "Code": 100161,
                    "Value": "The birth date can't be later than today.",
                    "Type": "toast",
                },
                {
                    "Code": 200240,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100243,
                    "Value": "Apple authorization failed.",
                    "Type": "toast",
                },
                {
                    "Code": 200280,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100180,
                    "Value": "No bindings found. Unable to unbind.",
                    "Type": "toast",
                },
                {"Code": 200230, "Value": "Payment canceled.", "Type": "toast"},
                {"Code": 200340, "Value": "Payment canceled.", "Type": "toast"},
                {
                    "Code": 100220,
                    "Value": "Login authorization canceled.",
                    "Type": "toast",
                },
                {"Code": 100221, "Value": "FB authorization failed.", "Type": "toast"},
                {
                    "Code": 100700,
                    "Value": "Sorry, you do not have access to the test server.",
                    "Type": "pop",
                },
                {
                    "Code": 200380,
                    "Value": "Please confirm the agreement(s) first.",
                    "Type": "toast",
                },
                {
                    "Code": 100150,
                    "Value": "Incorrect UID or Transfer Code",
                    "Type": "toast",
                },
                {
                    "Code": 200290,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 300201,
                    "Value": "The game is under maintenance.",
                    "Type": "pop",
                },
                {"Code": 200120, "Value": "Order creation failed.", "Type": "pop"},
                {
                    "Code": 100130,
                    "Value": "The account has been banned.",
                    "Type": "pop",
                },
                {
                    "Code": 100305,
                    "Value": "Current email address has been banned.",
                    "Type": "pop",
                },
                {
                    "Code": 200110,
                    "Value": "Monthly spending limits exceeded. Unable to create a new order.",
                    "Type": "toast",
                },
                {
                    "Code": 300209,
                    "Value": "API invoke failed. The text moderation function has not been enabled",
                    "Type": "pop",
                },
                {
                    "Code": 500305,
                    "Value": "Item synchronization failed. The field format is incorrect",
                    "Type": "toast",
                },
                {
                    "Code": 500300,
                    "Value": "Item synchronization failed. The item does not exist",
                    "Type": "toast",
                },
                {
                    "Code": 500306,
                    "Value": "Item synchronization failed. There are duplicate data",
                    "Type": "toast",
                },
                {
                    "Code": 100429,
                    "Value": "Too many codes sent, please try again later.",
                    "Type": "toast",
                },
                {
                    "Code": 200141,
                    "Value": "Order creation failed: Purchase currency is not supported",
                    "Type": "pop",
                },
                {
                    "Code": 100710,
                    "Value": "Graphic verification has been enabled, please restart the app to verify",
                    "Type": "toast",
                },
                {
                    "Code": 500303,
                    "Value": "Item synchronization failed. Batch import is busy",
                    "Type": "toast",
                },
                {
                    "Code": 500304,
                    "Value": "Item synchronization failed. Required fields have not been completed",
                    "Type": "toast",
                },
                {
                    "Code": 100711,
                    "Value": "Graphic verification failed, please try again",
                    "Type": "toast",
                },
                {
                    "Code": 100600,
                    "Value": "Interface parameter error. Invoke failed",
                    "Type": "none",
                },
                {
                    "Code": 400300,
                    "Value": "This account has completed its migration and cannot be migrated again",
                    "Type": "pop",
                },
                {"Code": 100601, "Value": "PID is invalid", "Type": "none"},
                {"Code": 300103, "Value": "Sharing cancelled", "Type": "none"},
                {"Code": 0, "Value": "Succeed.", "Type": "toast"},
                {
                    "Code": 100232,
                    "Value": "The account is not deleted. Unable to recover.",
                    "Type": "pop",
                },
                {"Code": 200153, "Value": "Order creation failed.", "Type": "pop"},
                {
                    "Code": 200154,
                    "Value": "Could not verify this purchase.",
                    "Type": "pop",
                },
                {
                    "Code": 200301,
                    "Value": "An error occrred in Amazon Pay",
                    "Type": "pop",
                },
                {
                    "Code": 110404,
                    "Value": "SDK migration function is not enabled. No migration URL is configured for the project",
                    "Type": "pop",
                },
                {
                    "Code": 100311,
                    "Value": "Verification failed, please try again",
                    "Type": "toast",
                },
                {
                    "Code": 100310,
                    "Value": "Verification failed, please try again",
                    "Type": "toast",
                },
                {
                    "Code": 200261,
                    "Value": "An error occrred in Amazon Pay",
                    "Type": "pop",
                },
                {
                    "Code": 200271,
                    "Value": "An error occrred in Amazon Pay",
                    "Type": "pop",
                },
                {
                    "Code": 110130,
                    "Value": "Login failed, please try again",
                    "Type": "toast",
                },
                {
                    "Code": 110110,
                    "Value": "Login failed, 2.X SDK service unavailable",
                    "Type": "pop",
                },
                {
                    "Code": 200281,
                    "Value": "An error occrred in Amazon Pay",
                    "Type": "pop",
                },
                {
                    "Code": 100140,
                    "Value": "Login failed, please try again.",
                    "Type": "toast",
                },
                {"Code": 200351, "Value": "Order creation failed.", "Type": "pop"},
                {
                    "Code": 200429,
                    "Value": "Apple's rate limit exceeded, retry attempts ongoing",
                    "Type": "toast",
                },
                {
                    "Code": 400900,
                    "Value": "Binding failed. This Yostar account does not exist.",
                    "Type": "pop",
                },
                {"Code": 200181, "Value": "Pending offline payment.", "Type": "toast"},
                {"Code": 200241, "Value": "0", "Type": "pop"},
                {
                    "Code": 200519,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 200606,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200603,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200218, "Value": "0", "Type": "pop"},
                {"Code": 200227, "Value": "0", "Type": "pop"},
                {
                    "Code": 200619,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200610,
                    "Value": "Please upgrade ONE store payment and try again.",
                    "Type": "pop",
                },
                {
                    "Code": 200511,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 200504,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 200512,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 600140, "Value": "Failed to match SDKUID.", "Type": "pop"},
                {"Code": 200213, "Value": "0", "Type": "pop"},
                {"Code": 200234, "Value": "0", "Type": "pop"},
                {"Code": 200245, "Value": "0", "Type": "pop"},
                {
                    "Code": 200616,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200621,
                    "Value": "Please upgrade ONE store payment and try again.",
                    "Type": "pop",
                },
                {
                    "Code": 200617,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200221, "Value": "0", "Type": "pop"},
                {
                    "Code": 200501,
                    "Value": "Please upgrade Samsung Pay and try again.",
                    "Type": "pop",
                },
                {
                    "Code": 200506,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200237, "Value": "0", "Type": "pop"},
                {
                    "Code": 200507,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200223, "Value": "0", "Type": "pop"},
                {"Code": 200251, "Value": "0", "Type": "pop"},
                {
                    "Code": 100225,
                    "Value": "Login authorization canceled.",
                    "Type": "toast",
                },
                {"Code": 200247, "Value": "0", "Type": "pop"},
                {"Code": 200202, "Value": "0", "Type": "pop"},
                {
                    "Code": 200602,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200618,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200215, "Value": "0", "Type": "pop"},
                {"Code": 200244, "Value": "0", "Type": "pop"},
                {"Code": 200203, "Value": "0", "Type": "pop"},
                {
                    "Code": 200513,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200209, "Value": "0", "Type": "pop"},
                {
                    "Code": 200505,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200156, "Value": "Order creation failed.", "Type": "pop"},
                {
                    "Code": 100133,
                    "Value": "Login or payment are not allowed because you do not meet the minimum age requirement.",
                    "Type": "pop",
                },
                {
                    "Code": 400145,
                    "Value": "Authorization failed. Please try again.",
                    "Type": "toast",
                },
                {"Code": 200249, "Value": "0", "Type": "pop"},
                {"Code": 200204, "Value": "0", "Type": "pop"},
                {"Code": 200229, "Value": "0", "Type": "pop"},
                {"Code": 200228, "Value": "0", "Type": "pop"},
                {"Code": 200216, "Value": "0", "Type": "pop"},
                {"Code": 200205, "Value": "0", "Type": "pop"},
                {"Code": 200155, "Value": "Payment failed.", "Type": "pop"},
                {
                    "Code": 200514,
                    "Value": "Please log in to Samsung Pay and try again.",
                    "Type": "pop",
                },
                {
                    "Code": 200509,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200236, "Value": "0", "Type": "pop"},
                {
                    "Code": 200613,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200615,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200601,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 600130,
                    "Value": "Failed to match SDK order ID.",
                    "Type": "pop",
                },
                {"Code": 200600, "Value": "Payment canceled.", "Type": "toast"},
                {"Code": 600120, "Value": "Duplicate data exists.", "Type": "pop"},
                {"Code": 200222, "Value": "0", "Type": "pop"},
                {"Code": 200208, "Value": "0", "Type": "pop"},
                {"Code": 200248, "Value": "0", "Type": "pop"},
                {"Code": 200212, "Value": "0", "Type": "pop"},
                {"Code": 200246, "Value": "0", "Type": "pop"},
                {
                    "Code": 200612,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200219, "Value": "0", "Type": "pop"},
                {"Code": 200211, "Value": "0", "Type": "pop"},
                {"Code": 200243, "Value": "0", "Type": "pop"},
                {
                    "Code": 200510,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 200607,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200502,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200238, "Value": "0", "Type": "pop"},
                {
                    "Code": 200620,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 600110, "Value": "Duplicate data exists.", "Type": "pop"},
                {"Code": 200210, "Value": "0", "Type": "pop"},
                {
                    "Code": 200516,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200225, "Value": "0", "Type": "pop"},
                {
                    "Code": 200605,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {
                    "Code": 200609,
                    "Value": "Please log in to ONE store and try again.",
                    "Type": "pop",
                },
                {"Code": 200224, "Value": "0", "Type": "pop"},
                {
                    "Code": 200515,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200200, "Value": "0", "Type": "pop"},
                {"Code": 600000, "Value": "0", "Type": "pop"},
                {"Code": 200217, "Value": "0", "Type": "pop"},
                {"Code": 200239, "Value": "0", "Type": "pop"},
                {
                    "Code": 200503,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 600100, "Value": "Tag does not exist.", "Type": "pop"},
                {
                    "Code": 200508,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 200604,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200242, "Value": "0", "Type": "pop"},
                {"Code": 200235, "Value": "0", "Type": "pop"},
                {"Code": 200253, "Value": "0", "Type": "pop"},
                {"Code": 200500, "Value": "Payment canceled.", "Type": "toast"},
                {"Code": 200206, "Value": "0", "Type": "pop"},
                {
                    "Code": 200614,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200233, "Value": "0", "Type": "pop"},
                {
                    "Code": 100320,
                    "Value": "Please use files with a maximum size of 5MB.",
                    "Type": "pop",
                },
                {"Code": 500401, "Value": "Field format is incorrect.", "Type": "pop"},
                {"Code": 200231, "Value": "0", "Type": "pop"},
                {
                    "Code": 200611,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200226, "Value": "0", "Type": "pop"},
                {"Code": 200232, "Value": "0", "Type": "pop"},
                {
                    "Code": 200517,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 200518,
                    "Value": "An error occurred in Samsung Pay.",
                    "Type": "pop",
                },
                {"Code": 200252, "Value": "0", "Type": "pop"},
                {"Code": 200214, "Value": "0", "Type": "pop"},
                {
                    "Code": 500400,
                    "Value": "Required fields are not completed.",
                    "Type": "pop",
                },
                {
                    "Code": 200608,
                    "Value": "An error occurred in ONE store payment.",
                    "Type": "pop",
                },
                {"Code": 200207, "Value": "0", "Type": "pop"},
                {"Code": 500403, "Value": "Failed to match SDKUID.", "Type": "pop"},
                {
                    "Code": 600900,
                    "Value": "The maximum number of tags has been reached.",
                    "Type": "pop",
                },
                {"Code": 200201, "Value": "0", "Type": "pop"},
                {"Code": 500402, "Value": "Duplicate data exists.", "Type": "pop"},
                {"Code": 201145, "Value": "Steam payment failed.", "Type": "pop"},
                {
                    "Code": 200400,
                    "Value": "Payment failed. Steam account status is abnormal.",
                    "Type": "pop",
                },
                {
                    "Code": 201182,
                    "Value": "This payment method is unavailable.",
                    "Type": "pop",
                },
                {"Code": 201235, "Value": "Steam payment timed out.", "Type": "pop"},
                {
                    "Code": 300404,
                    "Value": "Web authorization unavailable. Please add to the allowlist.",
                    "Type": "pop",
                },
                {
                    "Code": 600310,
                    "Value": "A maximum of 500 allowlist accounts per application.",
                    "Type": "pop",
                },
                {"Code": 201236, "Value": "Payment canceled.", "Type": "toast"},
                {
                    "Code": 400310,
                    "Value": "Account migration failed. This user already exists.",
                    "Type": "pop",
                },
                {"Code": 200161, "Value": "Order refund failed.", "Type": "pop"},
                {
                    "Code": 600200,
                    "Value": "Refund failed. This order does not needs a refund.",
                    "Type": "pop",
                },
                {
                    "Code": 600320,
                    "Value": "Products paid manually cannot be refunded.",
                    "Type": "pop",
                },
                {"Code": 200158, "Value": "Order creation failed.", "Type": "pop"},
                {"Code": 200157, "Value": "Order creation failed.", "Type": "pop"},
                {
                    "Code": 902404,
                    "Value": "This error code does not exist.",
                    "Type": "pop",
                },
                {"Code": 200159, "Value": "Order creation failed.", "Type": "pop"},
                {
                    "Code": 600300,
                    "Value": "A maximum of 500 test accounts per application.",
                    "Type": "pop",
                },
                {"Code": 200401, "Value": "Order creation failed.", "Type": "pop"},
                {"Code": 101401, "Value": "Steam authorization failed.", "Type": "pop"},
                {
                    "Code": 201232,
                    "Value": "This device does not support Apple Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 400320,
                    "Value": "Account migration failed. This account has already migrated.",
                    "Type": "pop",
                },
                {
                    "Code": 100241,
                    "Value": "Login authorization canceled.",
                    "Type": "toast",
                },
                {
                    "Code": 200330,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100244,
                    "Value": "Apple authorization failed.",
                    "Type": "toast",
                },
                {
                    "Code": 100233,
                    "Value": "The account has been in the cooling-off period for account deletion now.",
                    "Type": "pop",
                },
                {
                    "Code": 100245,
                    "Value": "Apple authorization failed.",
                    "Type": "toast",
                },
                {"Code": 300202, "Value": "The game is offline.", "Type": "pop"},
                {"Code": 100222, "Value": "TW authorization failed.", "Type": "toast"},
                {"Code": 100226, "Value": "Logging in, please wait.", "Type": "toast"},
                {
                    "Code": 200300,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100308,
                    "Value": "Refreshing too frequently, please try again later.",
                    "Type": "toast",
                },
                {
                    "Code": 200310,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100403,
                    "Value": "The login has expired, please log in again.",
                    "Type": "toast",
                },
                {
                    "Code": 100227,
                    "Value": "Google authorization failed.",
                    "Type": "toast",
                },
                {
                    "Code": 100302,
                    "Value": "Too many codes sent, please try again later.",
                    "Type": "toast",
                },
                {
                    "Code": 100404,
                    "Value": "Network error. Please connect again.",
                    "Type": "pop",
                },
                {
                    "Code": 100131,
                    "Value": "The account has been in the cooling-off period for account deletion now.",
                    "Type": "pop",
                },
                {
                    "Code": 200360,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 200250,
                    "Value": "An error occurred in Google Pay.",
                    "Type": "pop",
                },
                {
                    "Code": 100223,
                    "Value": "Google authorization failed.",
                    "Type": "toast",
                },
                {
                    "Code": 100160,
                    "Value": "You have set your birth date and it can't be changed.",
                    "Type": "toast",
                },
                {
                    "Code": 100400,
                    "Value": "System error. Please contact Customer Service.",
                    "Type": "pop",
                },
                {
                    "Code": 100110,
                    "Value": "Login failed, please try again.",
                    "Type": "toast",
                },
                {
                    "Code": 200150,
                    "Value": "Could not verify this purchase.",
                    "Type": "pop",
                },
                {
                    "Code": 200190,
                    "Value": "Could not verify this purchase.",
                    "Type": "pop",
                },
                {"Code": 200220, "Value": "Payment failed.", "Type": "pop"},
                {"Code": 100120, "Value": "Restricted IP.", "Type": "pop"},
                {
                    "Code": 200370,
                    "Value": "Order created. Unable to create it again.",
                    "Type": "pop",
                },
                {
                    "Code": 200100,
                    "Value": "Please set your birth date and try again.",
                    "Type": "none",
                },
                {"Code": 300100, "Value": "Failed to share.", "Type": "toast"},
            ]
        },
        "Msg": "OK",
    }
    return response


@router.post("/common/client-log")
async def common_client_log(request: Request):
    request_json = await request.json()
    response = {"Code": 200, "Data": {}, "Msg": "OK"}
    return response
